"""add device permission data and update owner role permissions

Permissions included:
- Team Devices
    - READ
    - MANAGE
    - DELETE

We also need to add permissions to team Owner role and team Member role.


Revision ID: 3d19e8d3338d
Revises: 5fce78f4bb4f
Create Date: 2024-09-30 09:51:45.776581

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.orm.session import Session

from app.database.migrations.repository import (
    delete_permissions,
    get_permission_ids_by_scopes,
    get_role_owner_ids,
    remove_owner_permissions,
    save_permissions,
    update_owner_permissions,
)
from app.models import Permission
from app.module.auth.permission import TeamDevicePermission

# revision identifiers, used by Alembic.
revision: str = "3d19e8d3338d"
down_revision: str | None = "5fce78f4bb4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


permissions = [
    Permission(scope=p.scope, title=p.title, description=p.description)
    for p in [
        # Team Devices
        TeamDevicePermission.READ,
        TeamDevicePermission.MANAGE,
        TeamDevicePermission.DELETE,
    ]
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Starting data migration for team device permissions")
    session = Session(bind=op.get_bind())

    # Add all permissions to the database
    save_permissions(session, permissions)

    # Update team Owner role permissions
    role_owner_ids = get_role_owner_ids(session)

    update_owner_permissions(session, role_owner_ids, permissions)

    session.commit()
    print("Data migration for team device permissions completed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Starting data rollback for team device permissions")
    session = Session(bind=op.get_bind())

    role_owner_ids = get_role_owner_ids(session)

    scopes = [p.scope for p in permissions]
    permission_ids = get_permission_ids_by_scopes(session, scopes)

    remove_owner_permissions(session, role_owner_ids, permission_ids)

    delete_permissions(session, permission_ids)

    session.commit()

    print("Data rollback for team device permissions completed")
    # ### end Alembic commands ###
