"""drop owner id col

Revision ID: 851c84f685bc
Revises: 91bb264f3ba7
Create Date: 2024-09-26 10:39:21.226110

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "851c84f685bc"
down_revision: str | None = "91bb264f3ba7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("teams_owner_id_fkey", "teams", type_="foreignkey")
    op.drop_column("teams", "owner_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(
        "teams_owner_id_fkey", "teams", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
