"""team invitation

Revision ID: c2ee710cd48a
Revises: 2f5eda52d82d
Create Date: 2024-08-15 14:51:16.271833

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2ee710cd48a"
down_revision: str | None = "2f5eda52d82d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("inviter_id", sa.UUID(), nullable=True),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.TEXT(), nullable=False),
        sa.Column("role", sa.TEXT(), nullable=False),
        sa.Column("token", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inviter_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_invitations")
    # ### end Alembic commands ###
