"""add joined at col

Revision ID: ff9eca3b14ed
Revises: 52e3a6414408
Create Date: 2024-09-26 15:33:51.250435

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff9eca3b14ed"
down_revision: str | None = "52e3a6414408"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_teams", sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_teams", "joined_at")
    # ### end Alembic commands ###
