"""init schemas

Revision ID: f8704f181c76
Revises:
Create Date: 2024-08-14 14:50:59.301833

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f8704f181c76"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
