"""add role permission data

Revision ID: 24d5a0f27b28
Revises: 3d19e8d3338d
Create Date: 2024-10-01 14:20:07.039025

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.orm.session import Session

from app.database.migrations.repository import (
    delete_permissions,
    get_permission_ids_by_scopes,
    get_role_owner_ids,
    remove_owner_permissions,
    save_permissions,
    update_owner_permissions,
)
from app.models import Permission
from app.module.auth.permission import TeamRolePermission

# revision identifiers, used by Alembic.
revision: str = "24d5a0f27b28"
down_revision: str | None = "3d19e8d3338d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

permissions = [
    Permission(scope=p.scope, title=p.title, description=p.description)
    for p in [
        # Team Roles
        TeamRolePermission.READ,
        TeamRolePermission.MANAGE,
        TeamRolePermission.DELETE,
    ]
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Starting data migration for team role permissions")
    session = Session(bind=op.get_bind())

    # Add all permissions to the database
    save_permissions(session, permissions)

    # Update team Owner role permissions
    role_owner_ids = get_role_owner_ids(session)

    update_owner_permissions(session, role_owner_ids, permissions)

    session.commit()
    print("Data migration for team role permissions completed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Starting data rollback for team role permissions")
    session = Session(bind=op.get_bind())

    role_owner_ids = get_role_owner_ids(session)

    scopes = [p.scope for p in permissions]
    permission_ids = get_permission_ids_by_scopes(session, scopes)

    remove_owner_permissions(session, role_owner_ids, permission_ids)

    delete_permissions(session, permission_ids)

    session.commit()

    print("Data rollback for team role permissions completed")
    # ### end Alembic commands ###
