"""add device data permission data

Permissions included:
- Team Device Data
    - READ
- Team Device Connect Log
    - READ
    - DELETE


Revision ID: e4598ec5a65e
Revises: 248483e1d27c
Create Date: 2024-10-08 08:45:43.824448

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.orm.session import Session

from app.database.migrations.repository import (
    delete_permissions,
    get_permission_ids_by_scopes,
    get_role_owner_ids,
    remove_owner_permissions,
    save_permissions,
    update_owner_permissions,
)
from app.models import Permission
from app.module.auth.permission import TeamDeviceConnectLogPermission, TeamDeviceDataPermission

# revision identifiers, used by Alembic.
revision: str = "e4598ec5a65e"
down_revision: str | None = "248483e1d27c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

permissions = [
    Permission(scope=p.scope, title=p.title, description=p.description)
    for p in [
        # Team Device Data
        TeamDeviceDataPermission.READ,
        # Team Device Connect Log
        TeamDeviceConnectLogPermission.READ,
        TeamDeviceConnectLogPermission.DELETE,
    ]
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Starting data migration for team device data permissions")
    session = Session(bind=op.get_bind())

    # Add all permissions to the database
    save_permissions(session, permissions)

    # Update team Owner role permissions
    role_owner_ids = get_role_owner_ids(session)

    update_owner_permissions(session, role_owner_ids, permissions)

    session.commit()
    print("Data migration for team device data permissions completed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Starting data rollback for team device data permissions")
    session = Session(bind=op.get_bind())

    permission_ids = get_permission_ids_by_scopes(session, [p.scope for p in permissions])

    role_owner_ids = get_role_owner_ids(session)

    remove_owner_permissions(session, role_owner_ids, permission_ids)

    delete_permissions(session, permission_ids)

    session.commit()
    print("Data rollback for team device data permissions completed")
    # ### end Alembic commands ###
