"""device data latest trigger

Revision ID: 248483e1d27c
Revises: 698610592768
Create Date: 2024-10-03 14:24:43.773937

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "248483e1d27c"
down_revision: str | None = "698610592768"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create function to update device_data_latest
    op.execute("""
        CREATE OR REPLACE FUNCTION update_device_data_latest_fn()
        RETURNS TRIGGER LANGUAGE PLPGSQL AS
        $BODY$
        BEGIN
            INSERT INTO device_data_latest AS ddl
                (device_id, ts, key, bool_v, str_v, long_v, double_v, json_v)
            VALUES
                (NEW.device_id, NEW.ts, NEW.key, NEW.bool_v, NEW.str_v, NEW.long_v, NEW.double_v, NEW.json_v)
            ON CONFLICT (device_id, key)
            DO UPDATE SET
                ts = CASE WHEN EXCLUDED.ts > ddl.ts THEN EXCLUDED.ts ELSE ddl.ts END,
                bool_v = CASE WHEN EXCLUDED.ts > ddl.ts THEN EXCLUDED.bool_v ELSE ddl.bool_v END,
                str_v = CASE WHEN EXCLUDED.ts > ddl.ts THEN EXCLUDED.str_v ELSE ddl.str_v END,
                long_v = CASE WHEN EXCLUDED.ts > ddl.ts THEN EXCLUDED.long_v ELSE ddl.long_v END,
                double_v = CASE WHEN EXCLUDED.ts > ddl.ts THEN EXCLUDED.double_v ELSE ddl.double_v END,
                json_v = CASE WHEN EXCLUDED.ts > ddl.ts THEN EXCLUDED.json_v ELSE ddl.json_v END;
            RETURN NULL;
        END
        $BODY$
    """)  # noqa: E501

    op.execute("ALTER TABLE device_data_latest SET (fillfactor = 90);")

    # Create trigger to update device_data_latest
    op.execute("""
        CREATE TRIGGER device_data_latest_trigger
        AFTER INSERT ON device_data
        FOR EACH ROW
        EXECUTE FUNCTION update_device_data_latest_fn();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER device_data_latest_trigger ON device_data;")

    op.execute("DROP FUNCTION update_device_data_latest_fn();")
    # ### end Alembic commands ###
